-- stylua: ignore
if true then return {} end

-- return {
--   "zbirenbaum/copilot.lua",
--   cmd = "Copilot",
--   event = "InsertEnter",
--   config = function()
--     require("copilot").setup({
--       filetypes = {
--         javascript = true,
--         typescript = true,
--         lua = true,
--       },
--     })
--   end,
--   init = function()
--     local wk = require("which-key")
--     wk.register({
--       ["<C-CR>"] = { 'copilot#Accept("\\<CR>")', "Accept Copilot suggestion" },
--     }, { mode = "i", expr = true, replace_keycodes = false })
--   end,
-- }
